steps:
- task: NAVMgtDockerStart@1
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/sandbox'
    docker_pull: true

- task: NAVMgtDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: NAVMgtLicenseImport@1
  displayName: 'ALOPS License Import'
  inputs:
    usedocker: true
    license_path: $(license)

- task: NAVMgtAppCompiler@2
  inputs:
    usedocker: true
    nav_app_version: '1.0.*.0'

- task: NAVMgtDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()